# Generated by Django 4.1.7 on 2023-05-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_surname', models.CharField(max_length=200)),
                ('bus_reg', models.CharField(max_length=200)),
                ('trip_time', models.CharField(max_length=200)),
                ('trip_date', models.CharField(max_length=200)),
                ('ticket_id', models.CharField(max_length=200)),
                ('trip_depature', models.CharField(max_length=500)),
                ('trip_destination', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_reg', models.CharField(max_length=200)),
                ('trip_time', models.CharField(max_length=200)),
                ('trip_date', models.CharField(max_length=200)),
                ('trip_depature', models.CharField(max_length=500)),
                ('trip_destination', models.CharField(max_length=500)),
            ],
        ),
    ]
