# Generated by Django 4.1.7 on 2023-04-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_reg', models.CharField(max_length=200)),
                ('trip_time', models.CharField(max_length=200)),
                ('trip_date', models.CharField(max_length=200)),
                ('trip_depature', models.CharField(max_length=500)),
                ('trip_destination', models.CharField(max_length=500)),
            ],
        ),
    ]
