# Generated by Django 4.1.7 on 2023-04-09 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_trips'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trips',
            new_name='Trip',
        ),
    ]
