# Generated by Django 4.1.7 on 2023-04-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_trips_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='trip_depature',
            new_name='trip_departure',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='trip_depature',
            new_name='trip_departure',
        ),
    ]
