# Generated by Django 4.1.7 on 2023-04-12 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_rename_trip_depature_booking_trip_departure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='trip_departure',
            new_name='trip_depature',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='trip_departure',
            new_name='trip_depature',
        ),
    ]
